-- 코드를 입력하세요
SELECT OUTS.ANIMAL_ID, OUTS.NAME
FROM ANIMAL_OUTS OUTS
INNER JOIN ANIMAL_INS INS
ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
WHERE DATEDIFF(OUTS.DATETIME, INS.DATETIME) > 0
ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC LIMIT 2;